steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - hello_world
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=python39
      - --memory=128MB
      - --timeout=60
      - --min-instances=0
      - --max-instances=1
      - --security-level=secure-always
      - --ingress-settings=all
      - --no-allow-unauthenticated
      - --service-account=interactive-map@my-map-358516.iam.gserviceaccount.com
